model_params:
  heads_params:
    logits: &num_classes {{ num_classes }}
    rotation_logits: &num_rotations 8
    class_rotation_logits: &num_class_rotations {{ num_classes * 8 }}

args:
  expdir: {{ expdir }}

stages:
  state_params:
    main_metric: &reduce_metric  auc_class/_mean
    minimize_metric: False

  data_params:
    num_workers: {{ num_workers }}
    batch_size: {{ batch_size }}
    per_gpu_scaling: True
    image_size: {{ max_image_size }}
    one_hot_classes: *num_classes
    balance_strategy: 1024
    in_csv_train: {{ dataset_path }}/dataset_train.csv
    in_csv_valid: {{ dataset_path }}/dataset_valid.csv
    datapath: {{ dataset_path }}/images

  criterion_params:
    _key_value: True

    class:
      criterion: FocalLossMultiClass
    rotation:
      criterion: CrossEntropyLoss
    class_rotation:
      criterion: CrossEntropyLoss  # FocalLossMultiClass

  callbacks_params:
    loss_class:
      callback: CriterionCallback
      input_key: targets
      output_key: logits
      prefix: loss_class
      criterion_key: class
    loss_rotation:
      callback: CriterionCallback
      input_key: rotation_factor
      output_key: rotation_logits
      prefix: loss_rotation
      criterion_key: rotation
    loss_class_rotation:
      callback: CriterionCallback
      input_key: class_rotation_targets
      output_key: class_rotation_logits
      prefix: loss_class_rotation
      criterion_key: class_rotation

    accuracy_class:
      callback: AccuracyCallback
      input_key: targets
      output_key: logits
      prefix: accuracy_class
      num_classes: *num_classes
    auc_class:
      callback: AUCCallback
      input_key: targets_one_hot
      output_key: logits
      prefix: auc_class
      num_classes: *num_classes
    cm_class:
      callback: ConfusionMatrixCallback
      input_key: targets
      output_key: logits
      prefix: cm_class
      num_classes: *num_classes

    accuracy_rotation:
      callback: AccuracyCallback
      input_key: rotation_factor
      output_key: rotation_logits
      prefix: accuracy_rotation
      accuracy_args: [1]
    cm_rotation:
      callback: ConfusionMatrixCallback
      input_key: rotation_factor
      output_key: rotation_logits
      prefix: cm_rotation
      num_classes: *num_rotations

    accuracy_class_rotation:
      callback: AccuracyCallback
      input_key: class_rotation_targets
      output_key: class_rotation_logits
      prefix: accuracy_class_rotation
      accuracy_args: *num_class_rotations

    optimizer:
      callback: OptimizerCallback
    scheduler:
      callback: SchedulerCallback
      reduce_metric: *reduce_metric
    saver:
      callback: CheckpointCallback
