model_params:
  model: MultiHeadNet
  encoder_params:
    arch: resnet18
    pretrained: True
    frozen: True
    pooling: GlobalConcatPool2d
  embedding_net_params:
    hiddens: [256]
    activation_fn: ReLU
    norm_fn: BatchNorm1d
    bias: false
    dropout: 0.5
  heads_params:
    logits: &num_classes 2

args:
  expdir: "src"
  logdir: &logdir "./logs/classification"
  baselogdir: "./logs/classification_base"

stages:

  state_params:
    main_metric: &reduce_metric accuracy01
    minimize_metric: False

  data_params:
    num_workers: 4
    batch_size: 64
    in_csv_train: "./data/dataset_train.csv"
    in_csv_valid: "./data/dataset_valid.csv"
    datapath: "./data/dataset"

  criterion_params:
    criterion: CrossEntropyLoss

  # train head
  stage1:

    state_params:
      num_epochs: 20

    optimizer_params:
      optimizer: Adam
      lr: 0.001
      weight_decay: 0.0001

    scheduler_params:
      scheduler: MultiStepLR
      milestones: [10]
      gamma: 0.3

    callbacks_params: &callbacks
      loss:
        callback: EmbeddingsLossCallback
        emb_l2_reg: -1
        input_key: targets
        embeddings_key: embeddings
        output_key: logits
      accuracy:
        callback: AccuracyCallback
        accuracy_args: [1]
      cm:
        callback: ConfusionMatrixCallback
        input_key: targets
        output_key: logits
        num_classes: *num_classes
      optimizer:
        callback: OptimizerCallback
      scheduler:
        callback: SchedulerCallback
        reduce_metric: *reduce_metric
      saver:
        callback: CheckpointCallback

  # tune whole network
  stage2:

    state_params:
      num_epochs: 10

    optimizer_params:
      optimizer: SGD
      lr: 0.0001

    scheduler_params:
      scheduler: MultiStepLR
      milestones: [10]
      gamma: 0.3

    callbacks_params: *callbacks

  infer:

    data_params:
      num_workers: 4
      batch_size: 64
      in_csv: null
      in_csv_train: null
      in_csv_valid: "./data/dataset_valid.csv"
      in_csv_infer: "./data/dataset_train.csv"
      datapath: "./data/dataset"
      one_hot_classes: null

    callbacks_params:
      loader:
        callback: CheckpointCallback
      infer:
        callback: InferCallback
        out_dir: *logdir
        out_prefix: "/predictions/"
